apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ticket-app-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /  # Réécriture des chemins vers la racine
spec:
  ingressClassName: nginx   # Classe d'Ingress à utiliser pour NGINX
  rules:
  - host: ticket-app.local    # Assure-toi que ce domaine est ajouté à ton fichier hosts
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: ticket-app-service   # Assure-toi que ce nom de service est correct
            port:
              number: 3000
