apiVersion: v1
kind: Service
metadata:
  name: ticket-app-service
  namespace: default
spec:
  selector:
    app: ticket-app
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
  type: NodePort

